GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "64dbee74d071c78f7631ff30"
}

###
DELETE  http://localhost:3001/api/notes/64d1b03e9eb3e9eac5b958c6